name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      max_version: ${{ steps.get-versions.outputs.max_version }}
      matrix: ${{ steps.get-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get versions
        id: get-versions
        run: |
          echo "max_version=$(tail -n 1 .python-versions)" >> $GITHUB_OUTPUT
          echo "matrix={\"python-version\": $(cat .python-versions | jq -R -s -c 'split("\n") | map(select(length > 0))')}" >> $GITHUB_OUTPUT

  ruff-lint:
    needs: get-python-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ needs.get-python-versions.outputs.max_version }}

      - name: Ruff lint
        run: uv run ruff check .

  ruff-format:
    needs: get-python-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ needs.get-python-versions.outputs.max_version }}

      - name: Ruff format check
        run: uv run ruff format --check .

  pyright:
    needs: get-python-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ needs.get-python-versions.outputs.max_version }}

      - name: Pyright type check
        run: uv run pyright

  pytest:
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-python-versions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
